### ISSUE TITLE
Can't unlock the 3rd cartridge and Purin

### ISSUE THREAD

**Issue by Dylalmob** [nebulazorua/full-restored#3]
You're supposed to press 7 in the shop then main menu to unlock the 3rd cartridge, but when I do that, literally nothing happens. And when I buy the blue candle, it tries to unlock Safety Lullaby for some reason. So the 3rd cartridge and Purin are both unobtainable.

**Comment by nebulazorua** [comment]
Those were not the intended unlock methods.

To unlock Missingno, you do it like lullaby v1 by "surfing" on the main menu (press down 3 times, then up 3 times, over and over.)
To unlock Purin, click the Pokemon Center in Safety Lullaby

**Comment by Dylalmob** [comment]
How many times do I have to "surf" in order to unlock Missingno?
